### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by schorlton-bugseq** [oxsecurity/megalinter#4591]
Thanks for your hard work on this tool! Running v8.4.0 via official docker image:

```python

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/megalinter/MegaLinter.py", line 51, in run_linters
    linter.run(run_commands_before_linters=False, run_commands_after_linters=False)
  File "/megalinter/Linter.py", line 819, in run
    pre_post_factory.run_linter_pre_commands(
  File "/megalinter/pre_post_factory.py", line 48, in run_linter_pre_commands
    return run_commands(
           ^^^^^^^^^^^^^
  File "/megalinter/pre_post_factory.py", line 97, in run_commands
    pre_command_result = run_command(command_info, log_key, mega_linter, linter)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/pre_post_factory.py", line 105, in run_command
    if command_info.get("cwd", "root") == "workspace":
       ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 14, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 252, in run
    self.process_linters_parallel(active_linters, linters_do_fixes)
  File "/megalinter/MegaLinter.py", line 391, in process_linters_parallel
    updated_linters = pool_result.get()
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: 'str' object has no attribute 'get'
```

Any ideas? v8.1.0 was the last version I was on and the same repo worked. Thanks!

**Comment by nvuillam** [comment]
Mmm this is in pre-post commands code... @bdovaz any idea ? :)

**Comment by nvuillam** [comment]
@schorlton-bugseq please can you share your PRE_COMMANDS config ?

**Comment by bdovaz** [comment]
Without @schorlton-bugseq config I would not be able to tell...

I have looked and seems that we have this test:

https://github.com/oxsecurity/megalinter/blob/main/megalinter/tests/test_megalinter/pre_post_test.py

https://github.com/oxsecurity/megalinter/tree/main/.automation/test/pre-post-test

That's why I thought that at least this test (which already existed before) covered the possible regressions for my PR but I see it doesn't?

**Comment by dtrinf** [comment]
> Thanks for your hard work on this tool! Running v8.4.0 via official docker image:
> 
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>                     ^^^^^^^^^^^^^^^^^^^
>   File "/megalinter/MegaLinter.py", line 51, in run_linters
>     linter.run(run_commands_before_linters=False, run_commands_after_linters=False)
>   File "/megalinter/Linter.py", line 819, in run
>     pre_post_factory.run_linter_pre_commands(
>   File "/megalinter/pre_post_factory.py", line 48, in run_linter_pre_commands
>     return run_commands(
>            ^^^^^^^^^^^^^
>   File "/megalinter/pre_post_factory.py", line 97, in run_commands
>     pre_command_result = run_command(command_info, log_key, mega_linter, linter)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/megalinter/pre_post_factory.py", line 105, in run_command
>     if command_info.get("cwd", "root") == "workspace":
>        ^^^^^^^^^^^^^^^^
> AttributeError: 'str' object has no attribute 'get'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/megalinter/run.py", line 14, in <module>
>     linter.run()
>   File "/megalinter/MegaLinter.py", line 252, in run
>     self.process_linters_parallel(active_linters, linters_do_fixes)
>   File "/megalinter/MegaLinter.py", line 391, in process_linters_parallel
>     updated_linters = pool_result.get()
>                       ^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 774, in get
>     raise self._value
> AttributeError: 'str' object has no attribute 'get'
> 
> Any ideas? v8.1.0 was the last version I was on and the same repo worked. Thanks!

I'm also facing the same problem, the previous working version for me was:

```
- Image Creation Date: 2024-11-23T10:43:56Z
- Image Revision: 1fc052d03c7a43c78fe0fee19c9d648b749e0c01
- Image Version: v8.3.0
````

**Comment by bdovaz** [comment]
> [@schorlton-bugseq](https://github.com/schorlton-bugseq) please can you share your PRE_COMMANDS config ? (Or even your whole .mega-linter.yml file ? )

Can any of you who are affected by it, put what @nvuillam asks? Thank you.

**Comment by dtrinf** [comment]
> > [@schorlton-bugseq](https://github.com/schorlton-bugseq) please can you share your PRE_COMMANDS config ? (Or even your whole .mega-linter.yml file ? )
> 
> Can any of you who are affected by it, put what [@nvuillam](https://github.com/nvuillam) asks? Thank you.

Sure, here you have my `.mega-linter.yml` file

```
# https://megalinter.io/latest/config-file/
# https://megalinter.io/latest/config-activation/
---
ENABLE_LINTERS:
  - TERRAFORM_TERRAFORM_FMT
  - TERRAFORM_TFLINT
# DISABLE_ERRORS_LINTERS:

## Terraform ##
TERRAFORM_TERRAFORM_FMT_DISABLE_ERRORS: false # break build on terraform formatting errors
TERRAFORM_FILTER_REGEX_INCLUDE: (deploy/terraform/continuous)
TERRAFORM_TFLINT_ARGUMENTS: --color

## Generic ##
EXCLUDED_DIRECTORIES: ["dasltools"]
FORMATTERS_DISABLE_ERRORS: false #break build on ALL formatting errors
VALIDATE_ALL_CODEBASE: true
CLEAR_REPORT_FOLDER: true
SHOW_SKIPPED_LINTERS: false
SECURED_ENV_VARIABLES:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_SESSION_TOKEN
```

**Comment by bdovaz** [comment]
@nvuillam looking at that file it looks like it has to do when you do NOT have pre/post commands.

**Comment by nvuillam** [comment]
Damn :o
So work around woukd be to add a dummy pre-command, meanwhile @bdovaz do u have availability to reproduce & fix the bug so i can release a patch tonight or tomorrow ?

**Comment by pjungermann** [comment]
We have i.e.
```
REPOSITORY_CHECKOV_PRE_COMMANDS:
  - command: export CKV_IGNORE_HIDDEN_DIRECTORIES=false
```
and it only fails for REPOSITORY_CHECKOV with that config. (We use pre-commands at a few other places, too.)

**Comment by pjungermann** [comment]
Maybe, it is (also) related to the bump to Python 3.12? 🤔 

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 14, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 252, in run
    self.process_linters_parallel(active_linters, linters_do_fixes)
  File "/megalinter/MegaLinter.py", line 391, in process_linters_parallel
    updated_linters = pool_result.get()
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: 'str' object has no attribute 'get'
```


For me, the error always happens after the execution of the first linter.


However, it does not happen/can be mitigated with
```yaml
PARALLEL: false
```

I tried adding pre-/post-commands but that didn't help.

```yaml
ENABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY

PRE_COMMANDS:
  - command: echo "Temporary mitigation for https://github.com/oxsecurity/megalinter/issues/4591"
    continue_if_failed: true
    cwd: workspace

POST_COMMANDS:
  - command: echo "Temporary mitigation for https://github.com/oxsecurity/megalinter/issues/4591"
    continue_if_failed: true
    cwd: workspace

REPOSITORY_PRE_COMMANDS:
  - command: echo "Temporary mitigation for https://github.com/oxsecurity/megalinter/issues/4591"
    continue_if_failed: true
    cwd: workspace

REPOSITORY_POST_COMMANDS:
  - command: echo "Temporary mitigation for https://github.com/oxsecurity/megalinter/issues/4591"
    continue_if_failed: true
    cwd: workspace

REPOSITORY_CHECKOV_PRE_COMMANDS:
  - command: echo "Temporary mitigation for https://github.com/oxsecurity/megalinter/issues/4591"
    continue_if_failed: true
    cwd: workspace

REPOSITORY_CHECKOV_POST_COMMANDS:
  - command: echo "Temporary mitigation for https://github.com/oxsecurity/megalinter/issues/4591"
    continue_if_failed: true
    cwd: workspace


REPOSITORY_TRIVY_PRE_COMMANDS:
  - command: echo "Temporary mitigation for https://github.com/oxsecurity/megalinter/issues/4591"
    continue_if_failed: true
    cwd: workspace

REPOSITORY_TRIVY_POST_COMMANDS:
  - command: echo "Temporary mitigation for https://github.com/oxsecurity/megalinter/issues/4591"
    continue_if_failed: true
    cwd: workspace
```

**Comment by pjungermann** [comment]
I realized it didn't happen for all flavors we use.

For the failing one (security), we have the following in a default/base config we extend:
```yaml
REPOSITORY_CHECKOV_PRE_COMMANDS:
  - command: some_command
```

Removing this pre-command helped as well.

**Comment by nvuillam** [comment]
@schorlton-bugseq @dtrinf @pjungermann @fostermarcp please can you check with beta version and confirm it's ok ?

(in 30mn, until the new beta is published by CI ^^ )

If i have positive feedback, I'll try to generate a patch tonight :)

**Comment by nvuillam** [comment]
All betas are published except cupcake flavor, tests can be performed :)

**Comment by fostermarcp** [comment]
I can go ahead and test it later today once the new beta version is pushed.

**Comment by nvuillam** [comment]
@fostermarcp it is ! :)

**Comment by fostermarcp** [comment]
seems successful. no error when using the beta version. 

- Image Creation Date: 2025-01-27T17:03:50.786Z
- Image Revision: 2c2208209e1c041480f41d01ca7c2b382048fa37
- Image Version: beta


+----SUMMARY----+-----------+---------------+-------+-------+--------+--------------+
| Descriptor    | Linter    | Mode          | Files | Fixed | Errors | Elapsed time |
+---------------+-----------+---------------+-------+-------+--------+--------------+
| ⚠️ REPOSITORY | gitleaks  | project       |   n/a |       |      3 |        2.49s |
| ⚠️ REPOSITORY | trivy     | project       |   n/a |       |      1 |       58.16s |
| ⚠️ TERRAFORM  | terrascan | project       |   n/a |       |      1 |       50.51s |
| ⚠️ TERRAFORM  | tflint    | project       |   n/a |       |      0 |        43.0s |
| ⚠️ YAML       | yamllint  | list_of_files |   373 |       |      8 |         6.5s |
+---------------+-----------+---------------+-------+-------+--------+--------------+

**Comment by fostermarcp** [comment]
Just wanted to leave a note: appreciate the super quick resposne and troubleshooting here. [nvuillam](https://github.com/nvuillam) you are amazing 🥇

**Comment by nvuillam** [comment]
> Just wanted to leave a note: appreciate the super quick resposne and troubleshooting here. [nvuillam](https://github.com/nvuillam) you are amazing 🥇 

Thanks :)
I work a lot, but i'm the a only one, my co maintainers @echoix and @bdovaz perform an amazing job, and we would do nothing without the help of the whole community 😋

(But if you want to post on LinkedIn/X/Reddit.... about MegaLinter, you are very welcome 😇)

**Comment by pjungermann** [comment]
I can confirm that it works with beta. Thank you for the quick resolution!

**Comment by nvuillam** [comment]
I release a patch tonight :)
I took 8 goals this evening at my soccer game (and i'm the goalkeeper), so at least i'll have a win for today 😂😂🤡
